package youxian.ncumap;

import java.util.List;

import com.google.android.gms.maps.model.BitmapDescriptorFactory;
import com.google.android.gms.maps.model.LatLng;
import com.google.android.gms.maps.model.MarkerOptions;

public class ViewMarker {
	List<MarkerOptions> markers;
	public ViewMarker(List<MarkerOptions> markers){
		this.markers=markers;
		setMarkers();
	}
	private void setMarkers() {
		// TODO Auto-generated method stub
		MarkerOptions m;
		m=new MarkerOptions();
		m.position(new LatLng(24.968285, 121.195299));
		m.title("行政大樓");
		m.icon(BitmapDescriptorFactory.fromResource(R.drawable.ic_building13));
		markers.add(m);
		m=new MarkerOptions();
		m.position(new LatLng(24.967273, 121.195696));
		m.title("校史館");
		m.icon(BitmapDescriptorFactory.fromResource(R.drawable.ic_building03));
		markers.add(m);
		m=new MarkerOptions();
		m.position(new LatLng(24.967011, 121.195717));
		m.title("據德樓");
		m.icon(BitmapDescriptorFactory.fromResource(R.drawable.ic_building11));
		markers.add(m);
		m=new MarkerOptions();
		m.position(new LatLng(24.966748, 121.195755));
		m.title("游藝館");
		m.icon(BitmapDescriptorFactory.fromResource(R.drawable.ic_building15));
		markers.add(m);
		m=new MarkerOptions();
		m.position(new LatLng(24.965769, 121.194139));
		m.title("女十四舍");
		m.icon(BitmapDescriptorFactory.fromResource(R.drawable.ic_building08));
		markers.add(m);
		m=new MarkerOptions();
		m.position(new LatLng(24.965778, 121.193664));
		m.title("志道樓");
		m.icon(BitmapDescriptorFactory.fromResource(R.drawable.ic_building05));
		markers.add(m);
		m=new MarkerOptions();
		m.position(new LatLng(24.968128, 121.193622));
		m.title("藝文中心");
		m.icon(BitmapDescriptorFactory.fromResource(R.drawable.ic_building01));
		markers.add(m);
		m=new MarkerOptions();
		m.position(new LatLng(24.968225, 121.194545));
		m.title("圖書館");
		m.icon(BitmapDescriptorFactory.fromResource(R.drawable.ic_building02));
		markers.add(m);
		m=new MarkerOptions();
		m.position(new LatLng(24.967826, 121.191804));
		m.title("資策會");
		m.icon(BitmapDescriptorFactory.fromResource(R.drawable.ic_building18));
		markers.add(m);
		m=new MarkerOptions();
		m.position(new LatLng(24.968298, 121.190956));
		m.title("依仁堂");
		m.icon(BitmapDescriptorFactory.fromResource(R.drawable.ic_building14));
		markers.add(m);
		m=new MarkerOptions();
		m.position(new LatLng(24.970041, 121.192892));
		m.title("綜教館");
		m.icon(BitmapDescriptorFactory.fromResource(R.drawable.ic_building09));
		markers.add(m);
		m=new MarkerOptions();
		m.position(new LatLng(24.970002, 121.192430));
		m.title("理學院");
		m.icon(BitmapDescriptorFactory.fromResource(R.drawable.ic_building05));
		markers.add(m);
		m=new MarkerOptions();
		m.position(new LatLng(24.970824, 121.192645));
		m.title("鴻經館");
		m.icon(BitmapDescriptorFactory.fromResource(R.drawable.ic_building10));
		markers.add(m);
		m=new MarkerOptions();
		m.position(new LatLng(24.970698, 121.193369));
		m.title("管二館");
		m.icon(BitmapDescriptorFactory.fromResource(R.drawable.ic_building07));
		markers.add(m);
		m=new MarkerOptions();
		m.position(new LatLng(24.969978, 121.193669));
		m.title("志希館");
		m.icon(BitmapDescriptorFactory.fromResource(R.drawable.ic_building11));
		markers.add(m);
		m=new MarkerOptions();
		m.position(new LatLng(24.970036, 121.194288));
		m.title("國鼎大樓");
		m.icon(BitmapDescriptorFactory.fromResource(R.drawable.ic_building06));
		markers.add(m);
		m=new MarkerOptions();
		m.position(new LatLng(24.970792, 121.194980));
		m.title("中大會館");
		m.icon(BitmapDescriptorFactory.fromResource(R.drawable.ic_building11));
		markers.add(m);
		m=new MarkerOptions();
		m.position(new LatLng(24.970247, 121.195404));
		m.title("男九舍");
		m.icon(BitmapDescriptorFactory.fromResource(R.drawable.ic_building01));
		markers.add(m);
		m=new MarkerOptions();
		m.position(new LatLng(24.970090, 121.190330));
		m.title("光電館");
		m.icon(BitmapDescriptorFactory.fromResource(R.drawable.ic_building06));
		markers.add(m);
		m=new MarkerOptions();
		m.position(new LatLng(24.970634, 121.190238));
		m.title("客家學院");
		m.icon(BitmapDescriptorFactory.fromResource(R.drawable.ic_building07));
		markers.add(m);
		m=new MarkerOptions();
		m.position(new LatLng(24.967565, 121.188421));
		m.title("工程三館");
		m.icon(BitmapDescriptorFactory.fromResource(R.drawable.ic_building17));
		markers.add(m);
		m=new MarkerOptions();
		m.position(new LatLng(24.967190, 121.187910));
		m.title("工程五館");
		m.icon(BitmapDescriptorFactory.fromResource(R.drawable.ic_building07));
		markers.add(m);
		
	}
}
